// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Rxhdkp7M3Gur3jspgcK1lU5BLwQhfjE',
    appId: '1:1084223372713:web:90f235ac93b79648d198b8',
    messagingSenderId: '1084223372713',
    projectId: 'chat-app-d31ce',
    authDomain: 'chat-app-d31ce.firebaseapp.com',
    storageBucket: 'chat-app-d31ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7uwYnOD5LCOjYqxGUaIDwvO4kwDAq6eQ',
    appId: '1:1084223372713:android:237ce94442569e33d198b8',
    messagingSenderId: '1084223372713',
    projectId: 'chat-app-d31ce',
    storageBucket: 'chat-app-d31ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGDkbO57jQJzxWblfx_zEkl9KV8Vs1Hg',
    appId: '1:1084223372713:ios:9b3dd4e38610c0c4d198b8',
    messagingSenderId: '1084223372713',
    projectId: 'chat-app-d31ce',
    storageBucket: 'chat-app-d31ce.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfGDkbO57jQJzxWblfx_zEkl9KV8Vs1Hg',
    appId: '1:1084223372713:ios:9b3dd4e38610c0c4d198b8',
    messagingSenderId: '1084223372713',
    projectId: 'chat-app-d31ce',
    storageBucket: 'chat-app-d31ce.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Rxhdkp7M3Gur3jspgcK1lU5BLwQhfjE',
    appId: '1:1084223372713:web:0595b92e40e10c6bd198b8',
    messagingSenderId: '1084223372713',
    projectId: 'chat-app-d31ce',
    authDomain: 'chat-app-d31ce.firebaseapp.com',
    storageBucket: 'chat-app-d31ce.appspot.com',
  );

}